### PR TITLE
Add 1.4.0 mapping for O365 Messagetrace Events

### PR DESCRIPTION
**Pull request by mikeradka**
This PR adds a `1.4.0` mapping for the Microsoft Office 365 Messagetrace Report event (`o365:reporting:messagetrace`).

Provided 1 raw sample and 1 corresponding OCSF translated sample for each possible `status_detail` value, which are:

```
"Delivered"
"Expanded"
"Failed"
"FilteredAsSpam"
"GettingStatus"
"None"
"Pending"
"Quarantined"
"Resolved"
```

Note: This event requires the `Trace` activity, introduced in version `1.4.0`. Therefore, `1.4.0` is the earliest OCSF version that supports this event mapping.

Caveat: When validating against the `1.4.0-dev` API, you will encounter one validation failure due to the `metadata.version` being set to `1.4.0` instead of `1.4.0-dev`. This was done intentionally to avoid changing the value in these examples once the `1.4.0` OCSF release is finalized.

```
  "errors": [
    {
      "error": "version_incorrect",
      "message": "Incorrect version at \"metadata.version\"; value of \"1.4.0\" does not match schema version \"1.4.0-dev\". This can result in incorrect validation messages.",
      "value": "1.4.0",
      "attribute": "version",
      "attribute_path": "metadata.version",
      "expected_value": "1.4.0-dev"
    }
  ]
```

### CODE REVIEW

**Review by irakledibm — APPROVED** [review]
lgfm

**Review by JW-Corelight — APPROVED** [review]
Makes sense - this is my first review, so i'm gonna miss stuff.  I like your (converted to epoch) note, and your Condition if/else definitions.

'type_uid' might belong up with the other static mapping table

**Comment by mikeradka** [comment]
> Makes sense - this is my first review, so i'm gonna miss stuff. I like your (converted to epoch) note, and your Condition if/else definitions.
> 
> 'type_uid' might belong up with the other static mapping table

Thanks @JW-Corelight . That is a good point about `type_uid`. Our tooling takes care of calculating/populating that field so my translation rule set doesn't statically map it per se, but for all intents and purposes it is a static field. So I moved it to over `static`.

**Review by JW-Corelight — APPROVED** [review]
Good context

**Comment by zschmerber** [comment]
[messagetrace/v1.0.4/README.md](https://github.com/ocsf/examples/pull/100/files#diff-520a6e7e65482773f35bf8df484893b6dcd0f68e25985410f63f5e5fdc8f37db)

folder name looks incorrect

**Comment by mikeradka** [comment]
> [messagetrace/v1.0.4/README.md](https://github.com/ocsf/examples/pull/100/files#diff-520a6e7e65482773f35bf8df484893b6dcd0f68e25985410f63f5e5fdc8f37db)
> 
> folder name looks incorrect

@zschmerber This was done to align with @JW-Corelight , some more info here: https://github.com/ocsf/examples/pull/94

We had an offline discussion about this, ultimately concluding that it is easier to browse/maintain a structure of `vendor -> product -> log -> ocsf version` instead of `vendor -> product -> ocsf version -> log`.

Not sure whether today is a good day to do a global change, but I would prefer for there to be a standard set. That said, I don't want this to hold up more examples going through.

**Comment by floydtree** [comment]
@mikeradka I think Zach meant 1.0.4 vs 1.4.0

**Comment by mikeradka** [comment]
> @mikeradka I think Zach meant 1.0.4 vs 1.4.0

Ah, great catch @zschmerber and thanks for the clarification @floydtree ! Corrected in the most recent commit, please re-review.

**Review by zschmerber — APPROVED** [review]

**Review by floydtree — APPROVED** [review]

**Review by irakledibm — APPROVED** [review]

**Pull request merged**
