### PR TITLE
Added mapping examples for Zeek logs

### PR DESCRIPTION
**Pull request by JW-Corelight**
Added mapping examples for Zeek logs

1. SSH
2. RDP
3. HTTP
4. SMTP
5. FTP

Updates for mapping examples for Zeek logs:
1. DNS
2. SSL

### CODE REVIEW

**Comment by floydtree** [comment]
Thanks for getting this out. If you are able to, can you also add samples, an input zeek log and it's normalized version. Basically, a story around the mapping (input -> mapping -> output). This will also help ensure, that the mapping is producing valid OCSF events. The OCSF server also has validation endpoint that you can use to validate.

**Comment by JW-Corelight** [comment]
Yes, I am building sample logs as per the instructions.  I have substantially more to contribute, so wanted to make sure I was getting the general formatting and structure correct in this first attempt.

**Comment by mavam** [comment]
I'm happy to take your mappings and contribute them to our existing Tenzir [Zeek package](https://github.com/tenzir/library/blob/main/zeek-ocsf/package.yaml) to produce valid OCSF.

**Comment by JW-Corelight** [comment]
That would be incredible - I’m just gonna be busy producing more of this
stuff near term, fyi

**Comment by mavam** [comment]
Great, if you have example logs with all the fields you added, we can add them to our test suite.

**Pull request closed without merging**
